language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121

script:
  # Run unit tests
  - cd test/Blockchain.Investments.Api.Tests/
  - dotnet restore
  - dotnet test
  - popd
#language: node_js
#node_js:
#  - 'stable'
#before_script:
#  - npm install -g grunt-cli bower
#  - bower install
#script: grunt test
#after_success:
#  - npm install -g codeclimate-test-reporter
#  - codeclimate-test-reporter < .tmp/coverage/report/lcov.info