language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121

script:
  # Run a new console app
  - mkdir -p "test/test-dotnet-new" && pushd "test/test-dotnet-new"
  - dotnet new
  - dotnet restore
  - dotnet --verbose run a b
  - popd
#language: node_js
#node_js:
#  - 'stable'
#before_script:
#  - npm install -g grunt-cli bower
#  - bower install
#script: grunt test
#after_success:
#  - npm install -g codeclimate-test-reporter
#  - codeclimate-test-reporter < .tmp/coverage/report/lcov.info