language: node_js
node_js:
  - 'stable'
before_script:
  - npm install -g grunt-cli bower
  - bower install
script: grunt test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < .tmp/coverage/report/lcov.info